### PR TITLE
Fixed bug with respect context in deps for elem mod

### LINKED ISSUE #112: deps tech does not respect context
https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/__dom/i-bem__dom.deps.js#L7
is treated as `i-bem_init` instead of `i-bem__dom_init`

### PR DESCRIPTION
**Pull request by blond**
Resolved #112

### CODE REVIEW

File: lib/deps/deps-resolver.js [hunk 1]
```diff
@@ -67,7 +67,13 @@ module.exports = inherit({
                 }
             } else if (dep.mod || dep.mods || dep.elems) {
                 if (dep.mod) {
-                    res.push({ name: dep.block || blockName, modName: dep.mod, modVal: dep.val });
+                    if (elemName) {
+                        res.push({ name: dep.block || blockName, elem: elemName, modName: dep.mod });
```
Comment (tadatuta) [inline lib/deps/deps-resolver.js]: I'd join both objects into one push() call. otherwise — lgtm
